### ISSUE TITLE
Extension won't build if a class has static properties

### ISSUE THREAD

**Issue by ironsand-sou-eu** [crxjs/rollup-plugin-chrome-extension#367]
### Build tool

Rollup

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

My chrome extension have classes, which have static properties, like this:

`    class MySiteScrapper extends SiteScrapper
    {
        static MY_HOME_PATH = "/domain/listing?idNumber="    
        // Other properties and methods
    }`

This code runs smoothly in the browser if I don't use the bundler, no problems at all (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static). But when I run `npm run build`, it stops in that line, with a Unexpected token exception pointing to the equal sign, and generates no distribution.

### Reproduction

N/A

### Logs

```shell
[!] (plugin chrome-extension) Error: Unexpected token
js\scrappers\tjba-projudi\ProjudiTjbaProcessoSiteScrapper.js (14:36)
12:     extends ProcessoSiteScrapper
13: {
14:     PROJUDI_TJBA_PROCESSO_HOME_PATH = "/projudi/listagens/DadosProcesso?numeroProcesso="
                                        ^
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 14.97 GB / 23.82 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    rollup: ^2.72.1 => 2.72.1
    rollup-plugin-chrome-extension: ^3.5.7 => 3.6.8
```

### Severity

blocking all usage of RPCE

**Comment by ironsand-sou-eu** [comment]
If you get any project with a class (any class) and add in the beggining a ```static MY_PROP = 'anything'```, are you able to parse it and create a distribution?

**Comment by jacksteamdev** [comment]
@ironsand-sou-eu This code builds for me:

![image](https://user-images.githubusercontent.com/23390212/167732705-0b5c5585-fc99-4165-9496-9e5efc6b12aa.png)

There are many things that could cause an issue like this. [Please include a repro.](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by jacksteamdev** [comment]
Please don't open duplicate discussions/issues. I'm happy to help if you can submit a minimum repro that I can use to verify the bug.

**Comment by ironsand-sou-eu** [comment]
Sorry for the duplicate entry, I thought both panes had different scopes. Here is my repo, I reinstalled it and the exception persisted: https://github.com/ironsand-sou-eu/SisifoRuyAndrade/tree/Rollup

**Comment by ironsand-sou-eu** [comment]
I can't really understand...  I received an e-mail from this issue discussion saying this plugin have not support anymore, but suddenly the message doesn't exists here. Is it true? This github page for RCEP is for a plugin which doesn't have support anymore? Couldn't you put some DEPRECATE warning, for unaware people not to use it? I don't intend to use React, I only wnat to bundle my extension... Can't I use Rollup anymore?

**Comment by ironsand-sou-eu** [comment]
Also, would you please remove the labels "could not reproduce" and "need more info"? I've already provided more info.

**Comment by ironsand-sou-eu** [comment]
I beg someone to answer me quickly, because I need to move on to some other solution if the ghost message I received is correct.

**Comment by jacksteamdev** [comment]
This bugfix was published to NPM in `rollup-plugin-chrome-extension@3.6.9`

**Comment by ironsand-sou-eu** [comment]
@jacksteamdev, thank you very very much for your attention! <3
